# Generated by Django 6.0 on 2026-03-09 23:00

import secrets
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('url', models.URLField()),
                ('events', models.JSONField(blank=True, default=list)),
                ('secret', models.CharField(default=secrets.token_hex, editable=False, max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('last_test_status', models.CharField(blank=True, max_length=20)),
                ('last_test_response', models.TextField(blank=True)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
