# Generated by Django 6.0 on 2026-02-26 16:33

from django.db import migrations, models


def sync_customer_status(apps, schema_editor):
    Customer = apps.get_model("parties", "Customer")
    Customer.objects.filter(is_active=False).update(status="inactive")


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], default='active', max_length=10),
        ),
        migrations.RunPython(sync_customer_status, migrations.RunPython.noop),
    ]
