# Generated by Django 6.0 on 2026-02-26 20:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Corporate', 'Corporate'), ('Product', 'Product'), ('Team', 'Team'), ('Client', 'Client'), ('Marketing', 'Marketing'), ('Technology', 'Technology')], max_length=20)),
                ('attendees', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='upcoming', max_length=10)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['date', 'created_at'],
            },
        ),
    ]
