# Generated by Django 6.0 on 2026-03-10 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notification_cartitem'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='notification',
                    name='level',
                    field=models.CharField(
                        choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')],
                        db_column='type',
                        default='info',
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
