# Generated by Django 6.0 on 2026-03-09 23:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0006_productvariant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('applicable_to', models.CharField(choices=[('products', 'Products'), ('categories', 'Categories'), ('both', 'Both')], max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('applicable_categories', models.ManyToManyField(blank=True, related_name='taxes', to='products.category')),
                ('applicable_products', models.ManyToManyField(blank=True, related_name='taxes', to='products.product')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
