# Generated by Django 5.2.7 on 2025-11-09 14:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
        ('parties', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytx',
            name='reason',
            field=models.CharField(choices=[('PURCHASE', 'Purchase'), ('SALE', 'Sale'), ('CYCLE_COUNT', 'Cycle Count'), ('CORRECTION', 'Correction'), ('DAMAGE', 'Damage'), ('LOSS', 'Loss'), ('RECEPTION', 'Reception'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.CreateModel(
            name='InventoryReception',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_received', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_received', models.DateField()),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('note', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parties.supplier')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.warehouse')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
