# Generated by Django 6.0 on 2026-02-25 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventorytx_reason_inventoryreception'),
        ('products', '0003_remove_product_brand_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_stocks', to='products.product'),
        ),
    ]
