# Generated by Django 6.0 on 2026-02-27 11:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_stock_product'),
        ('products', '0005_product_current_stock_product_last_restocked_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('in', 'In'), ('out', 'Out')], db_index=True, max_length=3)),
                ('quantity', models.PositiveIntegerField()),
                ('reason', models.CharField(max_length=120)),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('current_stock_after', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='products.product')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['product', 'type', 'date'], name='inventory_s_product_423ebb_idx'), models.Index(fields=['type', 'date'], name='inventory_s_type_031bf0_idx')],
            },
        ),
    ]
