# Generated by Django 6.0 on 2026-02-27 11:21

from django.db import migrations, models


def backfill_current_stock(apps, schema_editor):
    Product = apps.get_model("products", "Product")
    Product.objects.filter(current_stock=0, stock__gt=0).update(current_stock=models.F("stock"))


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productgalleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='current_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='last_restocked',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='min_stock',
            field=models.IntegerField(default=10),
        ),
        migrations.RunPython(backfill_current_stock, noop_reverse),
    ]
