# Generated by Django 6.0 on 2026-03-09 23:54

import django.db.models.deletion
from django.db import migrations, models


def add_parent_column_if_missing(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT 1
            FROM information_schema.columns
            WHERE table_name = 'products_category' AND column_name = 'parent_id'
            """
        )
        exists = cursor.fetchone() is not None

    if not exists:
        schema_editor.execute("ALTER TABLE products_category ADD COLUMN parent_id uuid NULL")

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT 1
            FROM pg_constraint c
            JOIN pg_class t ON t.oid = c.conrelid
            JOIN pg_attribute a ON a.attrelid = t.oid AND a.attnum = ANY(c.conkey)
            WHERE t.relname = 'products_category'
              AND a.attname = 'parent_id'
              AND c.contype = 'f'
            """
        )
        constraint_exists = cursor.fetchone() is not None

    if not constraint_exists:
        schema_editor.execute(
            """
            ALTER TABLE products_category
            ADD CONSTRAINT products_category_parent_id_fk
            FOREIGN KEY (parent_id)
            REFERENCES products_category (id)
            DEFERRABLE INITIALLY DEFERRED
            """
        )

    schema_editor.execute(
        "CREATE INDEX IF NOT EXISTS products_category_parent_id_idx ON products_category (parent_id)"
    )


def remove_parent_column(apps, schema_editor):
    schema_editor.execute("DROP INDEX IF EXISTS products_category_parent_id_idx")
    schema_editor.execute(
        "ALTER TABLE products_category DROP CONSTRAINT IF EXISTS products_category_parent_id_fk"
    )
    schema_editor.execute("ALTER TABLE products_category DROP COLUMN IF EXISTS parent_id")


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productvariant'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_parent_column_if_missing, remove_parent_column),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='category',
                    name='parent',
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='children',
                        to='products.category',
                    ),
                ),
            ],
        ),
    ]
