# Generated by Django 6.0 on 2026-03-11 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_category_parent'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE products_product DROP COLUMN IF EXISTS images;",
            reverse_sql="ALTER TABLE products_product ADD COLUMN images JSONB DEFAULT '[]'::jsonb;",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE products_product DROP COLUMN IF EXISTS thumbnail;",
            reverse_sql="ALTER TABLE products_product ADD COLUMN thumbnail VARCHAR(200);",
        ),
    ]
