# Generated by Django 6.0 on 2026-03-12 22:00

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_add_missing_product_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=core.storage.ProductImageStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='productgalleryimage',
            name='image',
            field=models.ImageField(storage=core.storage.ProductGalleryStorage(), upload_to=''),
        ),
    ]
