# Generated by Django 6.0 on 2026-03-12 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_image_alter_productgalleryimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('draft', 'Draft')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='productgalleryimage',
            name='image',
            field=models.ImageField(upload_to='products/gallery/'),
        ),
    ]
